name: Swift

on: [push]

jobs:
  iOS:
    name: iOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.7,name=iPhone 11 Pro']
        scheme: ['SwiftWings']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild clean test -project SwiftWings.xcodeproj -scheme SwiftWings -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          destination: ${{ matrix.destination }}
      - name: Upload Code Coverage
        run: bash <(curl -s https://codecov.io/bash) -J 'SwiftWings' -t ${{ secrets.CODECOV_TOKEN }}
